---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: check-docstring-first
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [
          aiomqtt>=2.3.0,
          pydantic>=2.9.0,
          pydantic-settings>=2.5.2,
          structlog>=24.4.0,
          PyYAML>=6.0.2,
          types-PyYAML>=6.0.12.20240917,
          uvloop>=0.20.0,
          prometheus-client>=0.21.0,
        ]
        args: [--ignore-missing-imports]
        # exclude: ^tests/
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
        args: [
          "--rcfile=pyproject.toml",
          "--fail-under=9.5"
        ]
