version: '3.8'

services:
  shelly-speedwire-gateway:
    image: dzikus99/shelly-speedwire-gateway:latest
    container_name: shelly-speedwire
    restart: unless-stopped
    network_mode: host  # REQUIRED for multicast/broadcast UDP
    environment:
      # MQTT Configuration - REQUIRED
      - MQTT_BROKER_HOST=192.168.1.123      # Change to your MQTT broker IP
      - MQTT_BASE_TOPIC=shellies/shellyem3-XXXXXXXXXXXX  # Change to your Shelly device ID

      # MQTT Optional Settings
      - MQTT_BROKER_PORT=1883
      - MQTT_KEEPALIVE=60
      - MQTT_INVERT_VALUES=false            # Set to true if CT clamps are mounted backwards
      - MQTT_QOS=1
      # - MQTT_USERNAME=mqtt_user           # Uncomment if auth required
      # - MQTT_PASSWORD=mqtt_pass           # Uncomment if auth required

      # Speedwire Configuration - REQUIRED
      - SPEEDWIRE_SERIAL=1234567890         # CHANGE TO UNIQUE SERIAL NUMBER!

      # Speedwire Optional Settings
      - SPEEDWIRE_INTERVAL=1.0
      - SPEEDWIRE_USE_BROADCAST=false
      - SPEEDWIRE_DUALCAST=false
      - SPEEDWIRE_SUSY_ID=349
      # - SPEEDWIRE_UNICAST_TARGETS=192.168.1.50,192.168.1.51  # Comma-separated IPs

      # Application Settings
      - LOG_LEVEL=INFO
      - LOG_FORMAT=structured
      - ENABLE_JIT=true
      - ENABLE_MONITORING=false
      - METRICS_PORT=8080

    # Option 1: Use environment variables (default)
    # Option 2: Mount your own config file (uncomment below)
    # volumes:
    #   - ./shelly_speedwire_gateway_config.yaml:/app/shelly_speedwire_gateway_config.yaml:ro

    # Optional: Monitoring port (if ENABLE_MONITORING=true)
    # ports:
    #   - "8080:8080"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
